extends Node

const CLIENT_HIGH_SCORE_PATH = "user://high_score.ini"
const CLIENT_VIEW_ABOUT = "CLIENT_VIEW_ABOUT"
const CLIENT_VIEW_ACHIEVEMENTS = "CLIENT_VIEW_ACHIEVEMENTS"
const CLIENT_VIEW_MAIN_MENU = "CLIENT_VIEW_MAIN_MENU"
const CLIENT_VIEW_NONE = "CLIENT_VIEW_NONE"
